amp: true
arch: UNext
aug: strong
batch_size: 8
dataset: busi
deep_supervision: false
early_stopping: -1
epochs: 100
factor: 0.1
freeze_except: null
gamma: 0.6666666666666666
img_ext: .png
init_from: models/busi_split42_aug/model.pth
input_channels: 3
input_h: 256
input_w: 256
loss: BCEDiceLoss
lr: 0.0001
mask_ext: .png
milestones: 1,2
min_lr: 1.0e-05
momentum: 0.9
n_params: 1471921
name: busi_split42_cont
nesterov: false
num_classes: 1
num_workers: 0
optimizer: Adam
patience: 2
resume: false
scheduler: CosineAnnealingLR
se_identity_init: false
se_reduction: 16
seed: 42
skip_identity_init: false
split_seed: 42
stop_after: null
weight_decay: 0.0001
